/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cstpb;

import com.google.protobuf.DescriptorProtos;
import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
}
